[package]
name = "mangata-primitives"
version = "0.1.0"
authors = ['Mangata team']
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"]}
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev-v0.9.24",  version = "6.0.0" }
sp-runtime = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev-v0.9.24",  version = "6.0.0" }

[features]
default = ["std"]
std = [
	'codec/std',
	'scale-info/std',
	'sp-core/std',
	'sp-runtime/std',
]
